name: photome
description: A photo sharing app built with flutter.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  device_preview: ^1.1.0
  file_picker: ^5.3.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  go_router: ^8.2.0
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.1
  supabase_flutter: ^1.10.4

dev_dependencies:
  build_runner: ^2.4.5
  custom_lint: ^0.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true

  assets:
    - .env
